### ISSUE TITLE
Issue when compiling vue-router

### ISSUE THREAD

**Issue by AlexandreBonaventure** [alanshaw/stripify#13]
Hi, just to let you know that we're using stripify for production build without any issue for some time but we stumble upon this error while using a new version of a lib (vue-router).

**To reproduce:**

```
npm i vue-router@2.0.0
browserify node_modules/vue-router/dist/vue-router.js -t stripify
```

I don't have much time to investigate but I thought maybe it will drag your attention.
Thanks

**Comment by alanshaw** [comment]
Can you post the error please?

**Comment by AlexandreBonaventure** [comment]
Here : 

```
SyntaxError: Unexpected token (148:2) while parsing /Users/alexandregeissmann/Sites/Lichen/Dokoma/dokoma_plus_app/node_modules/vue-router/dist/vue-router.js while parsing file: /Users/alexandregeissmann/Sites/Lichen/Dokoma/dokoma_plus_app/node_modules/vue-router/dist/vue-router.js
    at DestroyableTransform.end [as _flush] (/Users/alexandregeissmann/.npmglobal/lib/node_modules/browserify/node_modules/insert-module-globals/index.js:96:21)
    at DestroyableTransform.<anonymous> (/Users/alexandregeissmann/.npmglobal/lib/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at prefinish (/Users/alexandregeissmann/.npmglobal/lib/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:465:12)
    at finishMaybe (/Users/alexandregeissmann/.npmglobal/lib/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:473:7)
    at endWritable (/Users/alexandregeissmann/.npmglobal/lib/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:485:3)
    at DestroyableTransform.Writable.end (/Users/alexandregeissmann/.npmglobal/lib/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:455:41)
    at DestroyableTransform.onend (/Users/alexandregeissmann/Sites/Lichen/Dokoma/dokoma_plus_app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:495:10)
```
